name: J2xF
favicon: null
layout_spectrum: 0.04168454394675791
typography_spectrum: 0.5731835882179439
title: Slacker. Artist. Thinker.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7508103912696242
  lightness: 0.6874751173891127
  saturation: 0.3391946826595813
  rhythmicContrast: 0.16710825660265982
purpose: []
