name: J2xF
favicon: null
layout_spectrum: 0.25208
typography_spectrum: 0.0985
title: Slacker. Artist. Thinker.
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#8f5866'
    - '#060805'
    - '#114f38'
    - '#cecdc8'
  brandStrength: 0.5
  lightness: 0.6874751173891127
  saturation: 0.3125
  rhythmicContrast: 0.1671082566026598
purpose: []
