name: J2xF
favicon: null
layout_spectrum: 0.05175
typography_spectrum: 0.5731835882179439
title: Slacker. Artist. Thinker.
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#99cbfd'
    - '#999999'
    - '#323440'
  brandStrength: 0.5
  lightness: 0.6874751173891127
  saturation: 0.3125
  rhythmicContrast: 0.16710825660265982
purpose: []
