color:
  brandStrength: 0.5
  saturation: 0.3125
  brandColors:
    - '#ffffff'
    - '#000000'
    - '#99cbfd'
    - '#999999'
    - '#323440'
  lightness: 0.6874751173891127
  rhythmicContrast: 0.1671082566026598
title: Slacker. Artist. Thinker.
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  version: null
  bucket: null
  domain: null
favicon: null
layout_spectrum: 0.05175
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
purpose: []
name: J2xF
opengraph:
  image: null
  type: null
  appId: null
typography_spectrum: 0.0985
